services:
  web:
    container_name: web
    build: ./web
    ports:
      - '${WEB_PORT}:${WEB_PORT}'
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://localhost:${API_PORT}/api
    command: ['sh', '-c', 'PORT=${WEB_PORT} npm run start']

  api:
    container_name: api
    build: ./api
    init: true
    ports:
      - '${API_PORT}:${API_PORT}'
    volumes:
      - db-data:/app/db
    environment:
      - PORT=${API_PORT}
    command: ['sh', '-c', 'npm run migration:run && npm run start']

volumes:
  db-data:
